// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxgreejrqvxuoxyenwix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Z3JlZWpycXZ4dW94eWVud2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDI0MDIsImV4cCI6MjA1OTQxODQwMn0.NJ6wa8Fi9mYvo_yx1gOieUflLVTKcw1qmSrsuIGQ7lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);